### ISSUE TITLE
Turn org-roam-backlinks-mode into a minor-mode?

### ISSUE THREAD

**Issue by hubisan** [jethrokuan/org-roam#312]
Does `org-roam-backlinks-mode` have to be a major-mode? Or could it be a minor-mode? 

It might/does cripple some packages that work well with org as major-mode. 
Example: The very useful [link-hint](https://github.com/noctuid/link-hint.el).

**Comment by jethrokuan** [comment]
It became a major mode primarily to avoid overriding of keybindings, either way the backlinks buffer is due for a revamp.

**Comment by kljohann** [comment]
> It became a major mode primarily to avoid overriding of keybindings, either way the backlinks buffer is due for a revamp.

I think this could be achieved by removing `org-roam-open-at-point` in favor of a hook function that is put into `org-open-at-point-functions` when the (now minor) `org-roam-backlinks-mode` is active. Then the native `org-open-at-point` would "do the right thing" and as a plus, the user would not need to change their custom key bindings for this function. (Of course, if it was intentional to keep the original behavior of `org-open-at-point` in the backlinks buffer this would not work.)
This is possible because the first thing `org-open-at-point` does is to call
```elisp
(unless (run-hook-with-args-until-success 'org-open-at-point-functions)
  ...)
```
I think this change should not be too much effort and maybe it's worth it as an incremental step before revamping the backlinks buffer? If you are interested I can work on a pull request.

**Comment by jethrokuan** [comment]
@kljohann that sounds good. That may also make the minor mode obsolete, but I think some people depend on it being active to run some hooks.

**Comment by hubisan** [comment]
Key-bindings from a minor-mode should override major-mode ones.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Active-Keymaps.html#Active-Keymaps

> Usually, the active keymaps are: (i) the keymap specified by the keymap property, (ii) the keymaps of enabled minor modes, (iii) the current buffer's local keymap, and (iv) the global keymap, in that order. Emacs searches for each input key sequence in all these keymaps.

**Comment by hungpham2511** [comment]
I also find that having org-mode as the major mode useful. For instance navigation using ace-link is not possible in the backlink buffer.
