### ISSUE TITLE
Doing `org-roam-insert` during an `org-roam-insert` capture may cancel the first one.

### ISSUE THREAD

**Issue by brabalan** [jethrokuan/org-roam#327]
### Description

Doing `org-roam-insert` *for a new file* during an `org-roam-insert` *for a new file* capture cancels the first one: no link is introduced and the file is not saved.

#### Steps to Reproduce
1. start an `org-roam-insert` for a new file `foo`
2. in the capture buffer, do another `org-roam-insert` for a file `bar`
3. `C-c C-c`, bar is inserted as a link, and we return to the `foo` capture
4. `C-c C-c`, nothing is inserted, and the `foo` capture is lost

#### Expected Results
We don't lose the capture

#### Actual Results
We do

### Versions
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/4556f727ff1868d34b423bf1bc387136e2bf1a20

**Comment by jethrokuan** [comment]
`org-capture` doesn't support nested captures either, so this is difficult to implement.

**Comment by brabalan** [comment]
Maybe there should be a warning in the capture buffer then, because the loss of data can be quite inconvenient.

**Comment by jethrokuan** [comment]
oh nevermind I see what's going on.

**Comment by brabalan** [comment]
Thanks!

**Comment by brabalan** [comment]
I updated this morning and it does not seem to be fixed. Can you reproduce it on your side?

**Comment by jethrokuan** [comment]
It's fine for me now.

**Comment by jethrokuan** [comment]
It looks like org-capture no longer relies on data from the org-capture template after the template buffer is populated, which is why nested captures work. So supporting nested org-roam inserts would mean maintaining some form of call stack, but captures can be completed in random order (capture 1, capture 2 in capture 1, finish capture 1... what happens to capture 2?). This seems like it wouldn't be worth the complexity, so I'm going to throw an error on nested org-roam-inserts which creates new files.

**Comment by brabalan** [comment]
This make sense. Thanks!
