### ISSUE TITLE
Help with configuring multiple directories using .dir-locals.el (pls)

### ISSUE THREAD

**Issue by II-H** [jethrokuan/org-roam#394]
I'm not sure if I'm doing this right. I'm new to emacs.

So I'm doing my best to follow the steps documented in order to set up multiple file directories. 

I have a .dir-locals.el file with
`((nil . ((org-roam-directory . "~/nextcloud/org/notes/"))))`

inside of it. 

Should it be placed in my .emacs.d folder? Or should it be placed in the directory folder that it's pointing to? I've tried both approaches, and the second (after running `org-roam-db-build-cache`)[1] gives me an org-roam.db file in the notes directory shown, but the build results all show 0 (ie files: 0, links: 0, and so on) in emacs. 

Am I not understanding what "To add support for multiple directories, **override the org-roam-directory variable using directory-local variables**" means? Do I need to change anything in my ini.el file to correspond with these changes? I just pulled the latest update if that matters.

I apologize if this question is naive. Thank you to all involved with this project, boy, oh boy, this is a must-have package for anyone who is a note-taker.....again I'm new to emacs... and I hate to be that guy asking trivial questions on someone's github page because they aren't properly educated on how things work. 

Thanks again.

[1]: The [documentation](https://org-roam.readthedocs.io/en/latest/configuration/) still reads `org-roam-build-cache` by the way.

**Comment by jethrokuan** [comment]
Hi, sorry for the late reply. The dir-locals file should go into your alt org-roam directory. It might be showing 0s because there are no files changed.

You can check whether the org-roam-directory is set correctly by navigating to a file in that directory, and running C-h v org-roam-directory. That should rule out whether there is a misconfiguration.

**Comment by II-H** [comment]
No worries, I appreciate your response, period.

`C-h v org-roam-directory` in a .org file belonging to my secondary directory gives me the following:

> org-roam-directory is a variable defined in ‘org-roam.el’.
> Its value is "~/nextcloud/org/z"
> Original value was 
> "/Users/me/org-roam/"
> 
>   You can customize this variable.
> 
> Documentation:
> Default path to Org-roam files.
> 
> All Org files, at any level of nesting, is considered part of the Org-roam.

.dir-locals in also placed in the alt directory.

**Comment by jethrokuan** [comment]
Okay, so looks like that's setup correctly. Does `org-roam-find-file` show you any files? You'd have to be within your alt org-roam-directory, or it'll show you org-roam files from your main org-roam instance.

When you're in the file, does `org-roam` bring up a backlinks buffer that shows anything? Maybe @herbertjones can help better here, he's been using the multiple org-roam instance feature for a while now.

**Comment by II-H** [comment]
- `org-roam-find-file` in an alt-note shows only the files in my primary directory. 
- `org-roam-insert` returns "Not in an Org-roam file". 
- My backlinks buffer is blank

Thank you again.

**Comment by herbertjones** [comment]
If your second org-roam directory is `~/nextcloud/org/notes/`, inside of the file `~/nextcloud/org/notes/.dir-locals.el` I would put:

```elisp
((nil . ((eval . (setq-local org-roam-directory (expand-file-name "./"))))))
```

Once you modify a file inside that directory you will have to whitelist that eval for changes to take effect automatically.  You can set the variable to the exact path, but then if you move the directory around it would need to be reset to the new path.  Once it's confirmed that the dirs local file is updating the `org-roam-directory` variable correctly, then you may have to call `org-roam-db-build-cache`.

To make sure that `org-roam-directory` is getting updated, I'd normally just browse that directory with `dired` and run `describe-variable` on `org-roam-directory`.  When I do that I get the output:

```
org-roam-directory is a variable defined in ‘org-roam.el’.
Its value is "/home/herbert/Documents/personal-wiki/"
Original value was 
"/home/herbert/org-roam/"
Local in buffer personal-wiki; global value is "~/Sync/wiki"
```

If it isn't happening, then I'd look at https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html to see if there is something that looks out of place.  Also check the `*Messages*` buffer to see if any warnings are being recorded there.

**Comment by II-H** [comment]
Mr. Jones, thank you! Your instructions have done the trick and everything functions as intended. 

My final inquiries are as follows: _(feel free to keep the answers as succinct as necessary, i.e. "yes/no/we'll think about it", you each have already been enough help)_

-  It is possible for backlinks to register between directories? 
- Would repeating this procedure work if I wanted to implement a third, fourth and so on directory? (This is just for the sake of furthering my understanding of org-roam and the function of .dir-locals.el in general).

Again thank you, I appreciate the both of you taking the time to help me out with this. Feel free to close this per your own discretion.

**Comment by herbertjones** [comment]
In the past it was possible to have references between separate roam directories, as full paths are used as references to the files.  However you have to use the same (shared) database file for each directory instead of a separate database per directory.  You may be able to set `org-roam-db-location` to the same path for all the roam repositories you want to have references between.  I don't believe that is an intended feature, so I can't assure you it will currently work or will continue to work.

You can have as many roam directories as you want.  On one system I have 4 and it works fine for me.

**Comment by jethrokuan** [comment]
@herbertjones is full paths something you want working? It's just a tradeoff between portability of the files, and the functionality you mentioned above. It seems like something that can be added as a choice during link creation.

**Comment by herbertjones** [comment]
@jethrokuan If paths are relative now, that's great.  Currently I was not syncing the db files due to them being full paths.  Personally to me, roam links between directories doesn't seem like a feature that would be used much and could cause a lot of maintenance problems.

As for multi-dir extra functionality, I think a separate project could meet those needs.  Like I have a multi-dir `org-roam-find-file` that uses helm to find files from all my org-roam dirs.  However it needs to know all the paths to do that.  Such a project could also implement a multi-dir backlinks buffer, if it proves useful.  Maybe I'll get around to it once life gets a little more normal.

**Comment by priyakesavan** [comment]
Test comment.

**Comment by fremontmj** [comment]
Hi there,

I just followed herbertjones’ directions (thank you!). I’m wondering about two things I may not understand:

1. I ended up having to put the .dir-locals.el file in both directories; that makes sense to me, but since I didn’t see it in the above or the docs, I’m not sure if that is what I should have done.

2. To switch from one directory to another, unless I cd to the 2nd directory *and* visit a file in it via :edit, org-roam-find-file shows the files from the 1st directory. Is that the expected behavior?

THANK YOU for this FANTASTIC program. It is making my life way better.

**Comment by fremontmj** [comment]
Oops, sorry, just saw that my #1 was, in fact, explained in the thread. My bad!

**Comment by hraban** [comment]
@fremontmj to reply to your second question: visiting the file in your alternative directory only updates the `org-roam-directory` variable. That, in and of itself, doesn't have any further effect. Most org-roam actions (like `org-roam-find-file` don't use that variable---instead, they use the sqlite database which is built using `org-roam-db-build-cache`. That is called automatically every now and then (I'm never really sure when or why, exactly), but it doesn't happen immediately when you visit the first file. You can run it manually (`M-x org-roam-db-build-cache RET`), after which you should be good to go.
