### ISSUE TITLE
org-roam-insert should insert the filelink AFTER the normal mode cursor in evil

### ISSUE THREAD

**Issue by dit7ya** [jethrokuan/org-roam#4]
In evil mode when the cursor is in normal mode, you would expect the filelink to be written after the block cursor, in accordance with how paste works in evil mode. 

This is useful because you don't have to press space twice if you are habituated in evil, or spacemacs.

**Comment by jethrokuan** [comment]
I have no knowledge about evil whatsover, and how to design functions that play nice with evil. Maybe someone with more experience on this end can chime in.

**Comment by daniel-koudouna** [comment]
@dit7ya  I've run into this issue with a number of other packages. I'm still not sure exactly what the root cause is, but I've written my own fix for it. You can have a look here: 

https://gist.github.com/daniel-koudouna/39f03845914e34acde4d4c6a27c5176a

What it basically does it call the appropriate (move-forward) before executing the function. Binding a helper function as per the example should give you the expected behaviour.
