### ISSUE TITLE
Bug: org-roam-dailies-* functions "Wrong type argument: listp, 37"

### ISSUE THREAD

**Issue by OwenPriceSkelly** [jethrokuan/org-roam#500]
### Description
The org-roam-dailies-* functions are broken in doom emacs (pinned to "6175739b33"); pinning to "e33c1442" and using the old org-roam-today function works as expected.
#### Steps to Reproduce
1. Load (Doom) Emacs
2. Run `org-roam-dailies-today` or org-roam-dailies-tomorrow etc

#### Expected Results

loads note for daily roam file
#### Actual Results

messages buffer reads ""Wrong type argument: listp, 37"
### Versions
- Emacs (`C-h v emacs-version`): 26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/6175739b33b0abaa862c0137e216e6029f24d5cd

**Comment by mchowning** [comment]
I had a similar issue after https://github.com/jethrokuan/org-roam/pull/473 was merged, because I was using specifying `org-roam-date-filename-format` and `org-roam-date-title-format`, which that PR removed. Once I stopped setting those variables and set up `org-roam-dailies-capture-templates` I got things back to working the way I wanted:

```
  (setq org-roam-dailies-capture-templates
    '(("d" "daily" plain (function org-roam-capture--get-point)
       ""
       :immediate-finish t
       :file-name "daily/%<%Y-%m-%d>"
       :head "#+TITLE: %<%Y-%m-%d>")))
```

I'd give that a shot and see if that fixes your issue.

**Comment by OwenPriceSkelly** [comment]
That fixed it! thank you :)
