### ISSUE TITLE
Weird behavior when `dot` executable is nout found.

### ISSUE THREAD

**Issue by zoechi** [jethrokuan/org-roam#576]
#### Steps to Reproduce
- ensure `dot` executable is not found
- `M-x` `org-roam-graph`

> user-error: Can’t find nil executable.  Please check if it is in your path

- look up in source code what executable is required (`nil`) is not helpful
```sh
sudo apt install graphviz
```
- `M-x` `org-roam-graph`

> user-error: Can’t find nil executable.  Please check if it is in your path

- execute
```lisp
(setq org-roam-graph-executable "dot")
```
(or restart Emacs)

- `M-x` `org-roam-graph`

- Graph is finally shown

#### Expected Results
It should say what executable it is looking for (`dot`) and not drop this default value if `dot` is not found.
Then it would produce a proper error message 
and would try to find `dot` again after it was installed and all would be fine.

#### Actual Results
Confusing behavior

### Versions
- `GNU Emacs 28.0.50 (build 6, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-04-27`
- Org-roam commit: latest from elpa

**Comment by zaeph** [comment]
It's because `(executable-find "dot")` gets expanded to nil in the definition when `dot` couldn't be found in your `PATH`:
https://github.com/jethrokuan/org-roam/blob/3ca2d9f4caf688b14ad752e68cec74be0cb74ca6/org-roam-graph.el#L56-L59

We'd need to run an extra check here:
https://github.com/jethrokuan/org-roam/blob/3ca2d9f4caf688b14ad752e68cec74be0cb74ca6/org-roam-graph.el#L232
