### ISSUE TITLE
Better hook for `org-roam-update-buffer`

### ISSUE THREAD

**Issue by l3kn** [jethrokuan/org-roam#9]
Currently, a `post-command-hook` is used to update the buffer when another file is selected.

None of the [standard hooks](https://www.gnu.org/software/emacs/manual/html_node/elisp/Standard-Hooks.html) seems to run each time a buffer is opened or comes into focus.

The best solution I've found so far is adding an advice after the `select-window` function,
which works for all ways of selecting / opening an org file I've tested.

Maybe there is another hook / function that would be even better?

**Comment by jethrokuan** [comment]
I'm using `post-command-hook` because it's the suggestion here:

https://stackoverflow.com/questions/47456134/emacs-lisp-hooks-for-detecting-change-of-active-buffer

It looks like there's some hook in Emacs 27.1 that should do the trick, but I haven't tested that out. I've made the `post-command-hook` such that the org-roam buffer only updates when the file to display needs to change. The equality check feels cheap enough for me.
