### ISSUE TITLE
Recomposing text from zettels with #+INCLUDE or other?

### ISSUE THREAD

**Issue by anthrolisp** [jethrokuan/org-roam#97]
#4 and #5 of your blog post [How To Take Smart Notes With Org-mode](https://blog.jethro.dev/posts/how_to_take_smart_notes_org/)  are 4. Draw conclusions / outline text and 5. Write. 

How, in your workflow with org-roam, do you move from compose long form text from liked zettels (through hubs, explicit links, back links, etc)? Do you make use of the org-mode #+INCLUDE function? I know [zetteldeft](https://www.eliasstorms.net/zetteldeft/#orga36026d) uses it as part of its workflow. 

I'm curious to hear your thoughts.
Many thanks in advance!

**Comment by jethrokuan** [comment]
I suppose you're asking about how I use the notes to produce a written work.

I look through relevant and linked notes for points, and copy them out into a separate document and refine them into an essay. In Roam, I see a lot of people doing this within Roam itself. That works because Roam supports transclusion, while Emacs does not ([yet?](https://github.com/justintaft/emacs-transclusion)). Either way, this is not a problem for Org-roam to solve, you may choose to use external packages for this purpose.

Anyway you're looking at the 5 points of the "linear" (read "wrong") writing process, and I write later that I believe that's not how writing should be done.
